#+TODO: TODO(t) MAYBE(m) | DONE(d) NOTDONE(n)

* DONE Add option to delete snapshots not present in =from=
CLOSED: [2018-08-20 Mon 21:59]
* DONE Only show btrfs output as debug or verbose, add nicer messages
CLOSED: [2018-09-03 Mon 02:25]
** DONE Use Async_interactive jobs to display output nicely.
CLOSED: [2018-09-03 Mon 02:26]
* DONE Use shexp for process control
CLOSED: [2018-09-03 Mon 02:26]
* NOTDONE Use raw ~dup()~ calls instead of readers/writers
CLOSED: [2018-09-03 Mon 17:43]
Saves some extra layers in the pipeline
* TODO Warn if snapshot is not fully sent and marked readonly
https://ocaml.janestreet.com/ocaml-core/latest/doc/async_unix/Async_unix/Signal/
* NOTDONE Use pv as progress meter
CLOSED: [2021-02-24 Wed 20:12]
https://ivarch.com/programs/pv.shtml
* DONE sexp format config file in place of command-line interface
CLOSED: [2019-03-16 Sat 00:40]
Easier to specify structured arguments like local vs. ssh
* DONE Lockfile
CLOSED: [2019-03-16 Sat 00:52]
Probably do the sexp config file first, then use a lockfile to prevent the same
config being run multiple times concurrently.
* NOTDONE Warn if run outside screen/tmux session
CLOSED: [2021-02-24 Wed 20:11]
:LOGBOOK:
- Note taken on [2021-02-24 Wed 20:11] \\
  I now run snapsend as a systemd job, so this is no longer relevant.
:END:
snapsend can take a long time, so it is usually advisable to run it in tmux so
that you can easily disconnect your ssh session.
* DONE Log when not interactive
CLOSED: [2021-02-24 Wed 20:11]
:LOGBOOK:
CLOCK: [2021-02-24 Wed 19:30]--[2021-02-24 Wed 20:11] =>  0:41
:END:
Remove dependency on async_interactive and instead log using Async.Log.
